_templates:
  vHosts:
    default_vhost: &default_vhost
      port: 443
    a: &a
      <<: *default_vhost
      port: 443
      hostname: a.com
      cert: /certs/a.com.crt
      cert_key: /certs/a.com.key
      html_root: /sites/a.com/
    b: &b
      <<: *default_vhost
      port: 443
      hostname: b.com
      cert: /certs/b.com.crt
      cert_key: /certs/b.com.key
      html_root: /sites/b.com/
    c: &c
      <<: *default_vhost
      port: 443
      hostname: c.com
      cert: /certs/c.com.crt
      cert_key: /certs/c.com.key
      html_root: /sites/c.com/
    as: &as
      <<: *a
      stek_path: /a.com.stek.key
      stek_id: a.com
    bs: &bs
      <<: *b
      stek_path: /b.com.stek.key
      stek_id: b.com
    cs: &cs
      <<: *c
      stek_path: /c.com.stek.key
      stek_id: c.com
  default_server: &default_server
    stek_id: server1

test_cases:
  one-server:
    servers:
      - <<: *default_server
        vHosts:
        - *a
        - *b
        - *c
  one-server-different-steks:
    servers:
      - <<: *default_server
        vHosts:
        - *as
        - *bs
        - *cs
  one-server-different-ports:
    servers:
      - <<: *default_server
        vHosts:
        - *a
        - <<: *b
          port: 444
  two-servers-same-stek:
    servers:
      - <<: *default_server
        vHosts:
        - *a
      - <<: *default_server
        vHosts:
        - *b
  two-servers-same-stek-different-ports:
    servers:
      - <<: *default_server
        vHosts:
        - *a
      - <<: *default_server
        vHosts:
        - <<: *b
          port: 444
  two-servers-distinct-stek:
    servers:
      - <<: *default_server
        stek_id: server1
        vHosts:
        - *a
      - <<: *default_server
        stek_id: server2
        vHosts:
        - *b
  two-servers-distinct-stek-different-ports:
    servers:
      - <<: *default_server
        stek_id: server1
        vHosts:
        - *a
      - <<: *default_server
        stek_id: server2
        vHosts:
        - <<: *b
          port: 444

software_config:
  _base_config: &base_software
    stek_path: /stek.key
  nginx: &nginx
    <<: *base_software
    image: nginx:latest
    config_path: /etc/nginx/nginx.conf
    template: nginx.conf.jinja
    stek_length: 48
  nginx80:
    <<: *nginx
    stek_length: 80
  apache:
    <<: *base_software
    image: httpd:latest
    config_path: /usr/local/apache2/conf/httpd.conf
    template: apache.conf.jinja
    stek_length: 48
  openlitespeed:
    <<: *base_software
    image: litespeedtech/openlitespeed:latest
    config_path: /usr/local/lsws/conf/httpd_config.conf
    template: openlitespeed.conf.jinja
    stek_length: 48
